### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by jacobat** [pdamoc/elm-docset#1]
The doc page on Task provides more information than I can find in the docset which only provide type information.

**Comment by pdamoc** [comment]
Thanks for the report, I'll look more deeply to locate the source of that information (it is not coming from the documentation.json)

**Comment by pdamoc** [comment]
I have identified the source of the upgraded documentation and have updated the code to use it. 
The new version of the docset (v.1.0.1) has been created and the PR for the Dash User Contributions has been sent. 

Thank you again for the report.

**Comment by jacobat** [comment]
That was fast. Thanks Peter!
