### ISSUE TITLE
HTML tags in package summaries breaks the main docset index.

### ISSUE THREAD

**Issue by dannyob** [pdamoc/elm-docset#10]
I'm not sure if this is even visible on Dash, but the index.html generated in Elm.docset/Contents/Resources/Documents/ breaks if one of the summaries contains HTML tags (as massung/elm-css does).

The fix is to escape the summary string. I'm unsure whether others should be escaped, or whether pybars3 has its own better, global, escaping strategy than just using cgi.escape(), or whether more than just &, <, and > should be escaped.

I've included a minimal changeset just to fix this issue though.

**Comment by pdamoc** [comment]
Fixed by PR #11 

Thank you again.
