### ISSUE TITLE
Zeal reports that documentation feed is invalid

### ISSUE THREAD

**Issue by jacklenox** [pdamoc/elm-docset#12]
Thank you for creating this docset, I'm really keen to have this working in Zeal.

I followed the instructions [here](https://github.com/zealdocs/zeal/issues/170#issuecomment-71310603) to try to add the Elm docset to my installation of Zeal. I.e. click "Add feed" in Options > Docsets in Zeal, paste `http://london.kapeli.com/feeds/zzz/user_contributed/build/Elm/Elm.tgz`, click "Ok".

Zeal runs an uploading dialogue for a few seconds building up to 100%, then pops up an error, "Invalid docset feed!"

Any ideas what might be going wrong? I've downloaded the docset manually and it seems ok to me.

**Comment by pdamoc** [comment]
If the downloaded documentation works or if the locally generated documentation works then it is out of my control. Maybe it is a bug in Zeal. Maybe the kapeli hosting does something weird. Maybe Zeal is looking for something else in the link (i.e. not a .tgz but some kind of JSON/XML) 

Also, I never tested the docset in Zeal (I haven't bothered to create a linux VM). 

I'm going to close this issue now. If you can get some kind of more descriptive error from Zeal and there is something wrong with the docset, please either open a new issue or comment on this one.

**Comment by jacklenox** [comment]
Thanks for the reply, and sorry for hassling you with this!

It looks as though it is a problem with the Kapeli hosting. I didn't realise until this morning that I could just copy the unzipped `Elm.docset` into `~/.local/share/Zeal/Zeal/docsets`. Having done that, I can confirm that this docset seems to work fine in Zeal.

**Comment by mbylstra** [comment]
The approach of extracting the .tgz into the docsets dir worked for me the first time, but recently I tried downloading the most recent .tgz file and replacing the contents in ~/.local/share/Zeal/Zeal/docsets/Elm.docset. Zeal now crashes on launch - perhaps because the sqlite database needs to be updated somehow. I'm going to try to set up a proper xml feed.

**Comment by mbylstra** [comment]
You can now use this url as a feed: https://raw.githubusercontent.com/mbylstra/zeal-elm-docset-feed/master/Elm.xml. A big caveat though is that it never gets updated. It is a little easier pasting this url than unzipping the tarball into the Zeal directory though.
