### ISSUE TITLE
Error when generating docset

### ISSUE THREAD

**Issue by jacklenox** [pdamoc/elm-docset#16]
Thank you so much for this generator, I love it. However, on my most recent attempt to generate docs, I'm getting this error:

```
...
Generating package: capitalist/elm-octicons [ 82 / 683]...Traceback (most recent call last):
  File "generate.py", line 373, in <module>
    generate_all()
  File "generate.py", line 349, in generate_all
    html = toHtml(module.markdown).replace('<code>', '<code class="elm">') # fix syntax detection
  File "generate.py", line 277, in get_markdown
    ret.append(self.expand_docs(pre[len(pre_):]))
  File "generate.py", line 244, in expand_docs
    if item.startswith("docs"): item = item.split()[1]
IndexError: list index out of range
```

My Python is extremely limited, so I don't know what to make of this.

**Comment by pdamoc** [comment]
[The documentation of that package is a mess.](http://package.elm-lang.org/packages/capitalist/elm-octicons/2.0.0/Octicons). 

I'll push a fix that ignores that kind of error.

**Comment by jacklenox** [comment]
Thanks @pdamoc! All good now. :smile:
