### ISSUE TITLE
Update for Elm 0.19

### ISSUE THREAD

**Issue by sentience** [pdamoc/elm-docset#17]
How difficult would it be to update the docset now that Elm 0.19 is released? Would you like some help with this?

**Comment by pdamoc** [comment]
The way documentation works now is different from the way it did in `0.18`. I will research today the best way to move forward with this project. It might be easier to scrap it and move to a different architecture.

**Comment by pdamoc** [comment]
It turned out that it was easier than I anticipated. 😃 
Thank you for the push!
