### ISSUE TITLE
Unqualified indexed entry results

### ISSUE THREAD

**Issue by resolritter** [pdamoc/elm-docset#22]
I'm opening the issue here under the assumption that this is the same Docset as the one published in the  User Docsets Page, as disclosed in the README.

I'm using Zeal and when searching for e.g. "always", it retrieves even exports from random third-party packages. I wasn't sure of which of those options was actually the elm/core function because all of them are tagged as function with no further discrimination (it was the third one).

![image](https://user-images.githubusercontent.com/17429390/55771660-4fe03f00-5a5f-11e9-9dfc-4fab4e50c9a0.png)

I've found it's also impossible to narrow down the search, as in, querying for `List.map` doesn't work.

Would it be feasible to properly qualify all index entries, given that fuzzy matching will still catch  incomplete words if you want to be unspecific? I like that the whole ecosystem is bundled in there but between the conflicting names and multiple type-specific implementations, plus third-party packages exports overlap all over the place, makes this quite unusable for me.

**Comment by pdamoc** [comment]
There was [a PR](https://github.com/pdamoc/elm-docset/pull/19) in February that might have fixed this. 

This is only a generator, not the actual docset. I will generate a new version of the docset and upload it to Dash-User-Contributions (which is what I imagine that Zeal is using). 

In the mean time, if you don't want to wait, you can download the project and generate a fresh version for yourself.

**Comment by resolritter** [comment]
Indeed, I was using the old version and didn't know about that PR. Thanks so much for writing the generator!
