### ISSUE TITLE
Elm has a nice logo but it needn't dictate syntax highlighting

### ISSUE THREAD

**Issue by frou** [pdamoc/elm-docset#25]
Hi there - Thank you for providing this nice documentation. You know the green colour that's used in the docset for the colons and arrows in type signatures?

Its RGB value seems to have been picked directly off the Elm logo ([the tangram thing](https://en.wikipedia.org/wiki/Elm_(programming_language)#/media/File:Elm_logo.svg)), which is cute, but for actual use, that bright green colour is not very readable against a bright white background!

How about toning it down to an unassuming `#aaa` or something? I think it's set [here in the CSS](https://github.com/pdamoc/elm-docset/blob/master/assetts/style.css#L80).

cc @kraklin

**Comment by kraklin** [comment]
That’s probably a good idea. Let me try it out, I’m not sure how would it end up looking

**Comment by kraklin** [comment]
@frou - I have tried to change it a little bit, but I don't know... I have used the green colour that is right now used at package.elm-lang.com which is darker and for those types delimiter I have used `808080` - I kind of miss how the types stand out with the brighter green that is used right now to be honest. WDYT?

----
**current one:**
![Screenshot 2020-02-04 at 17 37 55](https://user-images.githubusercontent.com/1932160/73765652-1c506d00-4775-11ea-9afc-fcec8b208d86.png)

----
**new one:**
![Screenshot 2020-02-04 at 17 34 02](https://user-images.githubusercontent.com/1932160/73765667-25413e80-4775-11ea-81cd-d32b862eae63.png)

**Comment by frou** [comment]
I think that new style is great. In general if we consider what makes something visually stand out, it is not only colour, but shape too. Things like colons and arrows inherently stand out because their glyphs are interesting shapes.

I imagine people downloading the docset expect it to look like the official docs, just inside Dash. So moving in that direction is unlikely to outrage anyone!

**Comment by kraklin** [comment]
Yes, but I think I'll try to make those arrow delimiters a little bit more subtle though :D

**Comment by kraklin** [comment]
@frou ok, you asked for it - syntax highlighting uses the same colours as on package.elm-lang.com as well:

![Screenshot 2020-02-04 at 18 07 46](https://user-images.githubusercontent.com/1932160/73768492-60457100-4779-11ea-9cd8-75fa646e4a95.png)

^^ this is actual output of elm-docset, not screen from package.elm-lang.com :D

**Comment by frou** [comment]
Brilliant. This is a good stuff!

**Comment by kraklin** [comment]
Ok, I’ll try to deploy it with next update

**Comment by kraklin** [comment]
@frou it is there waiting to be merged in this pull request 
https://github.com/Kapeli/Dash-User-Contributions/pull/2655/files

**Comment by frou** [comment]
Thanks man, I appreciate it
