### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by mrmurphy** [pdamoc/elm-docset#4]
Hi, Peter!

What's your process for updating this docset? I've just cloned your repo and I'm generating the docsets over again at intervals for myself. But I'd like to offer my help if it's simple to publish the docsets I'm generating.

**Comment by pdamoc** [comment]
Hi, Murphy! 

I'm glad to see you are willing to help. 

Publishing the docsets is reasonably simple. Take a look at the User Contributions README:

https://github.com/Kapeli/Dash-User-Contributions

You need to pack the docset using the suggested command, place it in folder (delete the dummy Elm.tgz.txt), update the docset.json and the README to reflect the changes in version and author and then just create a pull request to push your modifications to the original Dash-User-Contributions repository. 

You will probably need to switch to a different naming scheme. Maybe 1.16.x  to follow the Elm 0.16 development. 

I don't remember the policy but you might need to mention in the pull request that you've taken over updating this docset. 

Once the PR gets merged in you can close this issue. 

Thank you again for doing this.

**Comment by mrmurphy** [comment]
Thanks, Peter! Here's the PR for reference:
https://github.com/Kapeli/Dash-User-Contributions/pull/870

**Comment by pdamoc** [comment]
Unfortunately, the pull request failed validation. I'll look and see what happens.

**Comment by pdamoc** [comment]
Hi Murphy, please pull the latest code, clear the cache by deleting the cache.json file and regenerate the Elm.docset. 

(as a side note, when I last did the docset, it was only about 70 packages, now there are 200... I did not knew that)

**Comment by mrmurphy** [comment]
Awesome, thanks for figuring that out. I can submit another PR to the Dash repo tomorrow morning
